--- 
- hosts: all
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        name: apache2

    - name: Install PHP support for Apache
      apt:
        name: libapache2-mod-php

