--- 
- hosts: all
  become: true 

  tasks:

    - name: update repository index 
      dnf:
        update_cache: yes

    - name: install Apache and PHP
      dnf:
        name:
          - httpd
          - php 
        state: latest
