[ubuntu]
s1javi ansible_host=192.168.56.120 ansible_user=s1javi
s2javi ansible_host=192.168.56.121 ansible_user=s2javi

[centos]
centjavi ansible_host=192.168.56.122 ansible_user=centjavi

[nagios_servers:children]
ubuntu
centos
